### PR TITLE
Added function to get base of a SDD-Node and tests

### PR DESCRIPTION
**Pull request by shreyas-kowshik**
@YitaoLiang Added the function as discussed.

### CODE REVIEW

**Comment by shreyas-kowshik** [comment]
@khosravipasha `Base` makes more sense for PSDD nodes rather than SDD nodes, I suppose.
Is there any other name you suggest for this?

**Comment by khosravipasha** [comment]
it's good I was just wondering what it means.

**Comment by YitaoLiang** [comment]
yeah, base is usually a concept associated with PSDD. It refers to the SDD (i.e. disregarding the parameters). Here, perhaps "to_string" would make sense?

**Comment by YitaoLiang** [comment]
Otherwise, it looks good to me. There could be some corner cases failing. But we can discuss that later, and update the code accordingly.

**Comment by khosravipasha** [comment]
Yeah, then something like `get_base_string` or `get_base_str` makes sense.

**Comment by shreyas-kowshik** [comment]
@khosravipasha Changed the name to `to_string` as using base does not seem to make sense in this context. Also made changes to accomodated `StructLogicalNodes` along with $\Delta$Node

**Comment by khosravipasha** [comment]
Sounds great, thanks for the change.

**Pull request merged**
