### PR TITLE
Add clone and merge candidates

### PR DESCRIPTION
**Pull request by shreyas-kowshik**
The older merge-candidates code that we were using was sort of a work-around.
This code is more updated. But it may have some bugs and we are currently figuring them out in our work as well.

### CODE REVIEW

**Comment by guyvdbroeck** [comment]
Thanks, this is certainly a useful addition. Any chance we can have a small unit test for it?

**Comment by shreyas-kowshik** [comment]
Let me add  tests for clone_candidates. 
For merge_candidates I believe the probabilistic-checking needs fixes as you pointed out and so perhaps we should add them after that is done?

**Comment by guyvdbroeck** [comment]
Let's indeed leave out `merge_candidates` for now, it has other concerns, for example that it requires a vtree.
Also then our code coverage does not decrease.
The `clone_candidates` looks good as is. In future, we'd like to avoid having to use `Dict` for this, since it's slow. One thing you could do is use the ability to count parents in `graphs.jl` by doing a `foreach` without resetting the `node.counter` field. Then you can do a filter based on the number of parents. Not sure if it would be faster, so not a priority.
If you remove the `merge_candidates` I will accept the pull request.

**Comment by shreyas-kowshik** [comment]
Removed `merge_candidates`

**Pull request merged**
